import { Router, type IRouter } from "express";
import healthRouter from "./health";
import metricsRouter from "./metrics";
import scentRouter from "./scent";
import adminRouter from "./admin";
import adminImagesRouter from "./adminImages";
import oauthRouter from "./oauth";
import meRouter from "./me";
import wardrobeRouter from "./wardrobe";
import shareRouter from "./share";
import communityRouter from "./community";
import communityPostsRouter from "./communityPosts";
import fragrancesRouter from "./fragrances";
import imageProxyRouter from "./imageProxy";
import imageObjectsRouter from "./imageObjects";
import scentFactsRouter from "./scentFacts";
import scentMissionRouter from "./scentMission";
import enrichmentRouter from "./enrichment";
import curationRouter from "./curation";
import usageRouter from "./usage";
import reviewsRouter from "./reviews";
import fragranceEngineProxyRouter from "./fragranceEngineProxy";
import pushRouter from "./push";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(metricsRouter);
router.use(scentRouter);
router.use(adminRouter);
router.use(adminImagesRouter);
router.use(oauthRouter);
router.use(meRouter);
router.use(wardrobeRouter);
router.use(shareRouter);
router.use(communityRouter);
router.use(communityPostsRouter);
router.use(fragrancesRouter);
router.use(imageProxyRouter);
router.use(imageObjectsRouter);
router.use(scentFactsRouter);
router.use(scentMissionRouter);
router.use(enrichmentRouter);
router.use(curationRouter);
router.use(usageRouter);
router.use(reviewsRouter);
router.use(fragranceEngineProxyRouter);
router.use(pushRouter);
router.use(notificationsRouter);

export default router;
