export type NoteFamilyWeight = {
  family: string;
  weight: number;
};

export type FamilyAccordMapping = {
  accord: string;
  weight: number;
};

export const NOTE_ALIASES: Record<string, readonly string[]> = {
  agarwood: ["oud"],
  "agarwood oud": ["oud"],
  ambrette: ["musk mallow"],
  "bitter orange": ["orange"],
  blackcurrant: ["cassis"],
  "cashmere wood": ["cashmeran wood"],
  cedarwood: ["cedar"],
  "elemi resin": ["elemi"],
  "elmi resin": ["elmi", "elemi resin", "elemi"],
  frankincense: ["olibanum"],
  "lily of the valley": ["muguet"],
  mahonial: ["mahonil", "mahonnel"],
  mahonil: ["mahonial", "mahonnel"],
  mahonnel: ["mahonial", "mahonil"],
  mandarin: ["mandarin orange"],
  "mandarin orange": ["mandarin"],
  oakmoss: ["oak moss"],
  olibanum: ["frankincense"],
  orris: ["iris"],
  petitgrain: ["petit grain"],
  "pink pepper": ["pink peppercorn"],
  tonka: ["tonka bean"],
  "white musk": ["musk"],
};

export const ACCORD_ALIASES: Record<string, readonly string[]> = {
  aldehydic: ["aldehydes"],
  amber: ["ambery"],
  balsamic: ["resin", "resinous", "amber"],
  citrus: ["citrusy"],
  floral: ["flower", "flowers", "white floral", "yellow floral"],
  fresh: ["freshness", "clean"],
  fruity: ["fruit", "fruits", "red fruits", "tropical"],
  green: ["leafy", "vegetal"],
  gourmand: ["edible", "dessert"],
  musky: ["musk", "white musk", "clean musk"],
  powdery: ["powder"],
  smoky: ["smoke", "incense"],
  spicy: ["warm spicy", "fresh spicy", "peppery"],
  woody: ["wood", "woods", "woodiness"],
};

export const NOTE_FAMILIES: Record<string, readonly NoteFamilyWeight[]> = {
  aldehyde: [{ family: "fresh", weight: 0.7 }],
  aldehydes: [{ family: "fresh", weight: 0.7 }],
  akigalawood: [{ family: "woody", weight: 1 }],
  almond: [
    { family: "gourmand", weight: 0.85 },
    { family: "sweet", weight: 0.55 },
  ],
  amber: [
    { family: "amber", weight: 1 },
    { family: "sweet", weight: 0.45 },
  ],
  ambergris: [
    { family: "amber", weight: 1 },
    { family: "marine", weight: 0.45 },
  ],
  ambrette: [
    { family: "musky", weight: 1 },
    { family: "powdery", weight: 0.35 },
  ],
  ambroxan: [
    { family: "amber", weight: 0.95 },
    { family: "woody", weight: 0.45 },
  ],
  apple: [
    { family: "fruity", weight: 1 },
    { family: "fresh", weight: 0.45 },
  ],
  apricot: [{ family: "fruity", weight: 1 }],
  basil: [
    { family: "aromatic", weight: 0.85 },
    { family: "green", weight: 0.65 },
  ],
  benzoin: [
    { family: "amber", weight: 0.9 },
    { family: "sweet", weight: 0.65 },
  ],
  bergamot: [
    { family: "citrus", weight: 1 },
    { family: "fresh", weight: 0.55 },
  ],
  berry: [{ family: "fruity", weight: 1 }],
  berries: [{ family: "fruity", weight: 1 }],
  birch: [
    { family: "woody", weight: 0.8 },
    { family: "smoky", weight: 0.45 },
  ],
  "birch tar": [
    { family: "smoky", weight: 1 },
    { family: "leather", weight: 0.8 },
  ],
  "bitter orange": [
    { family: "citrus", weight: 1 },
    { family: "fresh", weight: 0.45 },
  ],
  blackberry: [{ family: "fruity", weight: 1 }],
  blackcurrant: [{ family: "fruity", weight: 1 }],
  "black pepper": [{ family: "spicy", weight: 1 }],
  "blood orange": [
    { family: "citrus", weight: 1 },
    { family: "fruity", weight: 0.45 },
  ],
  bullrush: [
    { family: "green", weight: 0.85 },
    { family: "aquatic", weight: 0.45 },
  ],
  bulrush: [
    { family: "green", weight: 0.85 },
    { family: "aquatic", weight: 0.45 },
  ],
  cacao: [
    { family: "gourmand", weight: 1 },
    { family: "sweet", weight: 0.5 },
  ],
  calone: [
    { family: "aquatic", weight: 1 },
    { family: "fresh", weight: 0.65 },
  ],
  caramel: [
    { family: "gourmand", weight: 0.95 },
    { family: "sweet", weight: 0.85 },
  ],
  cardamom: [{ family: "spicy", weight: 1 }],
  carnation: [
    { family: "floral", weight: 0.85 },
    { family: "spicy", weight: 0.35 },
  ],
  cashmeran: [
    { family: "musky", weight: 0.75 },
    { family: "woody", weight: 0.55 },
  ],
  "cashmere wood": [
    { family: "woody", weight: 0.85 },
    { family: "musky", weight: 0.45 },
  ],
  cassis: [{ family: "fruity", weight: 1 }],
  cedar: [{ family: "woody", weight: 1 }],
  cedarwood: [{ family: "woody", weight: 1 }],
  champaca: [{ family: "floral", weight: 1 }],
  cherry: [{ family: "fruity", weight: 1 }],
  chocolate: [
    { family: "gourmand", weight: 1 },
    { family: "sweet", weight: 0.65 },
  ],
  cinnamon: [{ family: "spicy", weight: 1 }],
  cistus: [{ family: "amber", weight: 0.85 }],
  citron: [{ family: "citrus", weight: 1 }],
  "clary sage": [{ family: "aromatic", weight: 1 }],
  clove: [{ family: "spicy", weight: 1 }],
  "clean musk": [{ family: "musky", weight: 1 }],
  cocoa: [
    { family: "gourmand", weight: 1 },
    { family: "sweet", weight: 0.55 },
  ],
  coconut: [
    { family: "fruity", weight: 0.75 },
    { family: "gourmand", weight: 0.55 },
  ],
  coffee: [{ family: "gourmand", weight: 1 }],
  coriander: [
    { family: "spicy", weight: 0.85 },
    { family: "aromatic", weight: 0.45 },
  ],
  curry: [
    { family: "spicy", weight: 0.85 },
    { family: "aromatic", weight: 0.45 },
  ],
  earth: [{ family: "earthy", weight: 1 }],
  elemi: [
    { family: "amber", weight: 0.85 },
    { family: "spicy", weight: 0.45 },
  ],
  "elemi resin": [
    { family: "amber", weight: 0.9 },
    { family: "spicy", weight: 0.45 },
  ],
  elmi: [
    { family: "amber", weight: 0.85 },
    { family: "spicy", weight: 0.45 },
  ],
  "elmi resin": [
    { family: "amber", weight: 0.9 },
    { family: "spicy", weight: 0.45 },
  ],
  eucalyptus: [
    { family: "fresh", weight: 0.85 },
    { family: "green", weight: 0.55 },
  ],
  fennel: [
    { family: "aromatic", weight: 0.8 },
    { family: "green", weight: 0.45 },
    { family: "spicy", weight: 0.35 },
  ],
  fig: [
    { family: "fruity", weight: 0.85 },
    { family: "green", weight: 0.35 },
  ],
  "fig leaf": [{ family: "green", weight: 1 }],
  fir: [{ family: "woody", weight: 1 }],
  "fir needle": [
    { family: "woody", weight: 0.85 },
    { family: "green", weight: 0.55 },
  ],
  "fir resin": [
    { family: "woody", weight: 0.9 },
    { family: "amber", weight: 0.65 },
  ],
  frangipani: [{ family: "floral", weight: 1 }],
  frankincense: [
    { family: "smoky", weight: 0.85 },
    { family: "amber", weight: 0.65 },
  ],
  freesia: [{ family: "floral", weight: 1 }],
  galbanum: [
    { family: "green", weight: 1 },
    { family: "aromatic", weight: 0.45 },
  ],
  gardenia: [{ family: "floral", weight: 1 }],
  geranium: [
    { family: "floral", weight: 0.8 },
    { family: "aromatic", weight: 0.45 },
  ],
  ginger: [{ family: "spicy", weight: 1 }],
  grapefruit: [
    { family: "citrus", weight: 1 },
    { family: "fresh", weight: 0.5 },
  ],
  grass: [
    { family: "green", weight: 1 },
    { family: "fresh", weight: 0.45 },
  ],
  "green leaves": [{ family: "green", weight: 1 }],
  "green tea": [
    { family: "fresh", weight: 0.75 },
    { family: "green", weight: 0.65 },
  ],
  guaiac: [
    { family: "woody", weight: 0.9 },
    { family: "smoky", weight: 0.65 },
  ],
  "guaiac wood": [
    { family: "woody", weight: 0.95 },
    { family: "smoky", weight: 0.65 },
  ],
  heliotrope: [
    { family: "powdery", weight: 0.9 },
    { family: "floral", weight: 0.65 },
    { family: "gourmand", weight: 0.45 },
  ],
  honey: [
    { family: "sweet", weight: 0.9 },
    { family: "gourmand", weight: 0.55 },
  ],
  honeysuckle: [{ family: "floral", weight: 1 }],
  hyacinth: [
    { family: "floral", weight: 0.85 },
    { family: "green", weight: 0.45 },
    { family: "fresh", weight: 0.35 },
  ],
  incense: [{ family: "smoky", weight: 1 }],
  iris: [
    { family: "powdery", weight: 0.9 },
    { family: "floral", weight: 0.75 },
  ],
  "iso e super": [
    { family: "woody", weight: 0.85 },
    { family: "musky", weight: 0.45 },
  ],
  jasmine: [{ family: "floral", weight: 1 }],
  juniper: [
    { family: "aromatic", weight: 0.85 },
    { family: "green", weight: 0.35 },
  ],
  labdanum: [{ family: "amber", weight: 1 }],
  "labdanum resin": [{ family: "amber", weight: 1 }],
  lamb: [{ family: "amber", weight: 0.8 }],
  lavender: [{ family: "aromatic", weight: 1 }],
  leather: [{ family: "leather", weight: 1 }],
  lemon: [
    { family: "citrus", weight: 1 },
    { family: "fresh", weight: 0.55 },
  ],
  lilac: [{ family: "floral", weight: 1 }],
  lily: [{ family: "floral", weight: 1 }],
  "lily of the valley": [
    { family: "floral", weight: 1 },
    { family: "fresh", weight: 0.45 },
  ],
  lime: [
    { family: "citrus", weight: 1 },
    { family: "fresh", weight: 0.55 },
  ],
  lotus: [
    { family: "floral", weight: 0.85 },
    { family: "aquatic", weight: 0.45 },
  ],
  lychee: [{ family: "fruity", weight: 1 }],
  magnolia: [{ family: "floral", weight: 1 }],
  mahonial: [
    { family: "floral", weight: 0.85 },
    { family: "fresh", weight: 0.45 },
  ],
  mahonil: [
    { family: "floral", weight: 0.85 },
    { family: "fresh", weight: 0.45 },
  ],
  mahonnel: [
    { family: "floral", weight: 0.85 },
    { family: "fresh", weight: 0.45 },
  ],
  mandarin: [
    { family: "citrus", weight: 1 },
    { family: "fruity", weight: 0.45 },
  ],
  "mandarin orange": [
    { family: "citrus", weight: 1 },
    { family: "fruity", weight: 0.45 },
  ],
  mango: [{ family: "fruity", weight: 1 }],
  "marine notes": [
    { family: "aquatic", weight: 1 },
    { family: "fresh", weight: 0.65 },
  ],
  melon: [
    { family: "fruity", weight: 0.9 },
    { family: "fresh", weight: 0.35 },
  ],
  mimosa: [
    { family: "floral", weight: 0.75 },
    { family: "powdery", weight: 0.65 },
  ],
  mint: [
    { family: "fresh", weight: 0.85 },
    { family: "green", weight: 0.65 },
  ],
  moss: [{ family: "earthy", weight: 0.8 }],
  muguet: [
    { family: "floral", weight: 1 },
    { family: "fresh", weight: 0.45 },
  ],
  musk: [{ family: "musky", weight: 1 }],
  "musk mallow": [{ family: "musky", weight: 1 }],
  myrrh: [
    { family: "amber", weight: 0.85 },
    { family: "smoky", weight: 0.65 },
    { family: "spicy", weight: 0.35 },
  ],
  narcissus: [{ family: "floral", weight: 1 }],
  neroli: [
    { family: "floral", weight: 0.8 },
    { family: "fresh", weight: 0.55 },
    { family: "citrus", weight: 0.35 },
  ],
  nutmeg: [{ family: "spicy", weight: 1 }],
  oak: [{ family: "woody", weight: 0.8 }],
  "oak moss": [{ family: "earthy", weight: 0.85 }],
  oakmoss: [{ family: "earthy", weight: 0.85 }],
  olibanum: [
    { family: "smoky", weight: 0.85 },
    { family: "amber", weight: 0.65 },
  ],
  orange: [
    { family: "citrus", weight: 0.9 },
    { family: "fruity", weight: 0.45 },
  ],
  "orange blossom": [{ family: "floral", weight: 1 }],
  orchid: [{ family: "floral", weight: 1 }],
  orris: [
    { family: "powdery", weight: 0.95 },
    { family: "floral", weight: 0.65 },
  ],
  osmanthus: [
    { family: "floral", weight: 0.8 },
    { family: "fruity", weight: 0.35 },
  ],
  oud: [
    { family: "woody", weight: 1 },
    { family: "smoky", weight: 0.65 },
  ],
  "ozonic notes": [
    { family: "fresh", weight: 0.8 },
    { family: "aquatic", weight: 0.45 },
  ],
  patchouli: [
    { family: "woody", weight: 0.8 },
    { family: "earthy", weight: 0.75 },
  ],
  passionfruit: [{ family: "fruity", weight: 1 }],
  peach: [{ family: "fruity", weight: 1 }],
  pear: [
    { family: "fruity", weight: 1 },
    { family: "fresh", weight: 0.45 },
  ],
  peony: [{ family: "floral", weight: 1 }],
  pepper: [{ family: "spicy", weight: 1 }],
  petitgrain: [
    { family: "citrus", weight: 0.8 },
    { family: "green", weight: 0.6 },
    { family: "fresh", weight: 0.45 },
  ],
  pine: [{ family: "woody", weight: 1 }],
  "pine needle": [
    { family: "woody", weight: 0.85 },
    { family: "green", weight: 0.55 },
  ],
  pineapple: [{ family: "fruity", weight: 1 }],
  "pink pepper": [{ family: "spicy", weight: 1 }],
  plum: [{ family: "fruity", weight: 1 }],
  praline: [
    { family: "gourmand", weight: 0.95 },
    { family: "sweet", weight: 0.85 },
  ],
  raspberry: [{ family: "fruity", weight: 1 }],
  resin: [{ family: "amber", weight: 0.85 }],
  rockrose: [{ family: "amber", weight: 0.85 }],
  rose: [{ family: "floral", weight: 1 }],
  rosemary: [{ family: "aromatic", weight: 1 }],
  rosewood: [{ family: "woody", weight: 1 }],
  saffron: [
    { family: "spicy", weight: 0.8 },
    { family: "leather", weight: 0.45 },
  ],
  sage: [{ family: "aromatic", weight: 1 }],
  sandalwood: [
    { family: "woody", weight: 1 },
    { family: "musky", weight: 0.45 },
    { family: "creamy", weight: 0.35 },
  ],
  "sea salt": [
    { family: "aquatic", weight: 0.9 },
    { family: "fresh", weight: 0.55 },
  ],
  smoke: [{ family: "smoky", weight: 1 }],
  soil: [{ family: "earthy", weight: 1 }],
  spruce: [{ family: "woody", weight: 1 }],
  strawberry: [{ family: "fruity", weight: 1 }],
  suede: [{ family: "leather", weight: 1 }],
  sugar: [
    { family: "sweet", weight: 1 },
    { family: "gourmand", weight: 0.65 },
  ],
  tea: [
    { family: "fresh", weight: 0.65 },
    { family: "green", weight: 0.45 },
  ],
  thyme: [{ family: "aromatic", weight: 1 }],
  tobacco: [
    { family: "sweet", weight: 0.45 },
    { family: "smoky", weight: 0.45 },
  ],
  tomato: [{ family: "green", weight: 0.8 }],
  "tomato leaf": [{ family: "green", weight: 1 }],
  tonka: [
    { family: "gourmand", weight: 0.75 },
    { family: "powdery", weight: 0.55 },
    { family: "sweet", weight: 0.55 },
  ],
  "tonka bean": [
    { family: "gourmand", weight: 0.75 },
    { family: "powdery", weight: 0.55 },
    { family: "sweet", weight: 0.55 },
  ],
  tuberose: [{ family: "floral", weight: 1 }],
  vanilla: [
    { family: "gourmand", weight: 0.9 },
    { family: "sweet", weight: 0.85 },
  ],
  vetiver: [
    { family: "woody", weight: 0.7 },
    { family: "earthy", weight: 0.65 },
    { family: "green", weight: 0.35 },
  ],
  violet: [
    { family: "floral", weight: 0.85 },
    { family: "powdery", weight: 0.65 },
  ],
  "violet leaf": [{ family: "green", weight: 1 }],
  water: [
    { family: "aquatic", weight: 0.85 },
    { family: "fresh", weight: 0.55 },
  ],
  "water lily": [
    { family: "floral", weight: 0.85 },
    { family: "aquatic", weight: 0.45 },
  ],
  "white musk": [{ family: "musky", weight: 1 }],
  wood: [{ family: "woody", weight: 1 }],
  woods: [{ family: "woody", weight: 1 }],
  ylang: [{ family: "floral", weight: 1 }],
  "ylang ylang": [{ family: "floral", weight: 1 }],
  yuzu: [
    { family: "citrus", weight: 1 },
    { family: "fresh", weight: 0.55 },
  ],
};

export const FAMILY_TO_ACCORD_MAPPINGS: Record<string, readonly FamilyAccordMapping[]> = {
  amber: [
    { accord: "amber", weight: 1 },
    { accord: "ambery", weight: 1 },
    { accord: "balsamic", weight: 0.95 },
    { accord: "resinous", weight: 0.9 },
    { accord: "resin", weight: 0.85 },
  ],
  aquatic: [
    { accord: "aquatic", weight: 1 },
    { accord: "marine", weight: 0.9 },
    { accord: "water", weight: 0.75 },
    { accord: "ozonic", weight: 0.65 },
    { accord: "fresh", weight: 0.45 },
  ],
  aromatic: [
    { accord: "aromatic", weight: 1 },
    { accord: "herbal", weight: 0.9 },
    { accord: "lavender", weight: 0.85 },
    { accord: "anise", weight: 0.7 },
    { accord: "green", weight: 0.45 },
  ],
  citrus: [
    { accord: "citrus", weight: 1 },
    { accord: "citrusy", weight: 1 },
    { accord: "fresh", weight: 0.45 },
    { accord: "fruity", weight: 0.35 },
  ],
  creamy: [
    { accord: "creamy", weight: 1 },
    { accord: "lactonic", weight: 0.85 },
    { accord: "sweet", weight: 0.35 },
  ],
  earthy: [
    { accord: "earthy", weight: 1 },
    { accord: "mossy", weight: 0.85 },
    { accord: "patchouli", weight: 0.75 },
    { accord: "vetiver", weight: 0.7 },
    { accord: "woody", weight: 0.45 },
  ],
  floral: [
    { accord: "floral", weight: 1 },
    { accord: "white floral", weight: 0.95 },
    { accord: "yellow floral", weight: 0.9 },
    { accord: "rose", weight: 0.85 },
    { accord: "violet", weight: 0.75 },
    { accord: "powdery", weight: 0.35 },
  ],
  fresh: [
    { accord: "fresh", weight: 1 },
    { accord: "freshness", weight: 1 },
    { accord: "clean", weight: 0.8 },
    { accord: "aldehydic", weight: 0.75 },
    { accord: "green", weight: 0.45 },
    { accord: "aquatic", weight: 0.4 },
  ],
  fruity: [
    { accord: "fruity", weight: 1 },
    { accord: "fruit", weight: 1 },
    { accord: "red fruits", weight: 0.9 },
    { accord: "tropical", weight: 0.85 },
    { accord: "sweet", weight: 0.35 },
  ],
  gourmand: [
    { accord: "gourmand", weight: 1 },
    { accord: "vanilla", weight: 0.9 },
    { accord: "chocolate", weight: 0.85 },
    { accord: "caramel", weight: 0.85 },
    { accord: "sweet", weight: 0.65 },
  ],
  green: [
    { accord: "green", weight: 1 },
    { accord: "leafy", weight: 0.9 },
    { accord: "vegetal", weight: 0.85 },
    { accord: "fresh", weight: 0.45 },
  ],
  leather: [
    { accord: "leather", weight: 1 },
    { accord: "suede", weight: 0.85 },
    { accord: "smoky", weight: 0.4 },
  ],
  marine: [
    { accord: "marine", weight: 1 },
    { accord: "aquatic", weight: 0.9 },
    { accord: "salty", weight: 0.75 },
    { accord: "fresh", weight: 0.45 },
  ],
  musky: [
    { accord: "musky", weight: 1 },
    { accord: "musk", weight: 1 },
    { accord: "clean musk", weight: 0.95 },
    { accord: "white musk", weight: 0.95 },
    { accord: "powdery", weight: 0.35 },
  ],
  powdery: [
    { accord: "powdery", weight: 1 },
    { accord: "powder", weight: 1 },
    { accord: "iris", weight: 0.75 },
    { accord: "floral", weight: 0.35 },
  ],
  smoky: [
    { accord: "smoky", weight: 1 },
    { accord: "smoke", weight: 1 },
    { accord: "incense", weight: 0.9 },
    { accord: "woody", weight: 0.4 },
  ],
  spicy: [
    { accord: "spicy", weight: 1 },
    { accord: "warm spicy", weight: 0.95 },
    { accord: "fresh spicy", weight: 0.9 },
    { accord: "pepper", weight: 0.85 },
    { accord: "curry", weight: 0.8 },
  ],
  sweet: [
    { accord: "sweet", weight: 1 },
    { accord: "vanilla", weight: 0.75 },
    { accord: "honey", weight: 0.75 },
    { accord: "gourmand", weight: 0.65 },
  ],
  woody: [
    { accord: "woody", weight: 1 },
    { accord: "wood", weight: 1 },
    { accord: "woods", weight: 1 },
    { accord: "woodiness", weight: 1 },
    { accord: "cedar", weight: 0.9 },
    { accord: "sandalwood", weight: 0.9 },
    { accord: "oud", weight: 0.9 },
    { accord: "conifer", weight: 0.75 },
    { accord: "pine", weight: 0.75 },
    { accord: "fir", weight: 0.75 },
  ],
};

export const BROAD_NOTE_FAMILY_TERMS: Record<string, readonly string[]> = {
  amber: ["amber", "ambergris", "ambroxan", "labdanum", "benzoin", "myrrh", "elemi", "elmi", "cistus", "rockrose"],
  aquatic: ["aquatic", "marine", "sea salt", "water", "calone", "bulrush", "bullrush"],
  aromatic: ["lavender", "rosemary", "sage", "thyme", "basil", "juniper", "clary sage", "fennel", "curry"],
  citrus: ["bergamot", "lemon", "lime", "grapefruit", "mandarin", "orange", "yuzu", "citron", "petitgrain"],
  earthy: ["earth", "soil", "moss", "oakmoss", "patchouli", "vetiver"],
  floral: [
    "rose",
    "peony",
    "lily",
    "lily of the valley",
    "jasmine",
    "iris",
    "violet",
    "tuberose",
    "orange blossom",
    "ylang ylang",
    "neroli",
    "magnolia",
    "gardenia",
    "freesia",
    "honeysuckle",
    "lilac",
    "orchid",
    "osmanthus",
    "mimosa",
    "geranium",
    "carnation",
    "narcissus",
    "hyacinth",
    "lotus",
    "water lily",
    "champaca",
    "frangipani",
    "heliotrope",
    "mahonial",
    "mahonil",
    "mahonnel",
    "muguet",
  ],
  fresh: ["aldehyde", "aldehydes", "mint", "eucalyptus", "green tea", "tea", "marine", "ozone", "ozonic"],
  fruity: [
    "apple",
    "pear",
    "peach",
    "plum",
    "apricot",
    "blackcurrant",
    "cassis",
    "berry",
    "berries",
    "raspberry",
    "strawberry",
    "blackberry",
    "cherry",
    "fig",
    "melon",
    "pineapple",
    "mango",
    "passionfruit",
    "lychee",
    "coconut",
  ],
  gourmand: ["vanilla", "caramel", "praline", "chocolate", "cacao", "coffee", "honey", "sugar", "almond", "tonka"],
  green: [
    "galbanum",
    "green leaves",
    "grass",
    "violet leaf",
    "fig leaf",
    "tomato leaf",
    "tomato",
    "basil",
    "mint",
    "petitgrain",
    "hyacinth",
    "fennel",
    "bulrush",
    "bullrush",
    "pine needle",
    "fir needle",
  ],
  leather: ["leather", "suede", "saffron", "birch tar"],
  musky: ["musk", "white musk", "clean musk", "ambrette", "cashmeran", "sandalwood", "iso e super"],
  powdery: ["iris", "orris", "violet", "heliotrope", "mimosa", "tonka", "powder"],
  smoky: ["smoke", "incense", "olibanum", "frankincense", "myrrh", "birch tar", "guaiac wood", "oud"],
  spicy: ["pepper", "pink pepper", "cardamom", "cinnamon", "clove", "nutmeg", "saffron", "ginger", "coriander", "fennel", "curry"],
  sweet: ["vanilla", "tonka", "benzoin", "honey", "caramel", "praline", "sugar", "amber"],
  woody: [
    "wood",
    "woods",
    "fir",
    "fir resin",
    "balsam fir",
    "pine",
    "spruce",
    "cedar",
    "cedarwood",
    "sandalwood",
    "patchouli",
    "vetiver",
    "agarwood",
    "oud",
    "guaiac",
    "guaiac wood",
    "rosewood",
    "birch",
    "oak",
    "cashmere wood",
    "akigalawood",
    "iso e super",
  ],
};
